// Documentation each rule is based on. Referenced from the `source` field of every issue.
export const SOURCES = {
  title: 'https://developers.google.com/search/docs/appearance/title-link',
  snippet: 'https://developers.google.com/search/docs/appearance/snippet',
  canonical: 'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls',
  redirects: 'https://developers.google.com/search/docs/crawling-indexing/301-redirects',
  httpStatus: 'https://developers.google.com/search/docs/crawling-indexing/http-network-errors',
  fileTypes: 'https://developers.google.com/search/docs/crawling-indexing/indexable-file-types',
  googleImages: 'https://developers.google.com/search/docs/appearance/google-images',
  starterGuide: 'https://developers.google.com/search/docs/fundamentals/seo-starter-guide',
  lighthouse: 'https://developer.chrome.com/docs/lighthouse/overview',
  cls: 'https://web.dev/articles/optimize-cls',
  lcp: 'https://web.dev/articles/lcp',
  tbt: 'https://web.dev/articles/tbt',
  decorativeImages: 'https://www.w3.org/WAI/tutorials/images/decorative/',
  headings: 'https://www.w3.org/WAI/tutorials/page-structure/headings/',
  openGraph: 'https://ogp.me/',
  robotsMeta: 'https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag',
  viewport: 'https://developer.chrome.com/docs/lighthouse/pwa/viewport',
  languageOfPage: 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html',
  structuredData: 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data',
  searchGallery: 'https://developers.google.com/search/docs/appearance/structured-data/search-gallery',
  productSnippet: 'https://developers.google.com/search/docs/appearance/structured-data/product-snippet',
  breadcrumb: 'https://developers.google.com/search/docs/appearance/structured-data/breadcrumb',
  urlStructure: 'https://developers.google.com/search/docs/crawling-indexing/url-structure',
  googlebot: 'https://developers.google.com/search/docs/crawling-indexing/googlebot',
  javascriptSeo: 'https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics',
  robotsTxt: 'https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt',
  sitemaps: 'https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap',
  mixedContent: 'https://web.dev/articles/what-is-mixed-content'
}
